common/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.urls import include, path
from django.views.generic import TemplateView

from common.views import SettingsView

urlpatterns = [
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("partners/", include("partners.urls", namespace="partners")),
    path("invoices/", include("invoices.urls", namespace="invoices")),
    path("servers/", include("servers.urls", namespace="servers")),
    path("settings/", SettingsView.as_view(), name="settings"),
    path(
        "",
        login_required(TemplateView.as_view(template_name="dashboard.html")),
        name="dashboard",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invoices/urls.py
from django.urls import path

from invoices import views

app_name = "invoices"

urlpatterns = [
    path("", views.ListView.as_view(), name="list"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("<int:uid>/", views.PDFView.as_view(), name="pdf"),
    path("<int:uid>/edit/", views.EditView.as_view(), name="edit"),
    path("<int:uid>/delete/", views.DeleteView.as_view(), name="delete"),
]

partners/urls.py
from django.urls import path

from partners import views

app_name = "partners"

urlpatterns = [
    path("", views.ListView.as_view(), name="list"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("<int:uid>/", views.DetailView.as_view(), name="detail"),
    path("<int:uid>/edit/", views.EditView.as_view(), name="edit"),
    path("<int:uid>/delete/", views.DeleteView.as_view(), name="delete"),
]

partners/models.py
from decimal import Decimal

from django.db import models
from django_countries.fields import CountryField


class Partner(models.Model):
    uid = models.AutoField(primary_key=True)
    partner_id = models.CharField(
        max_length=3,
        unique=True,
        error_messages={"unique": "This Partner ID is already in use."},
    )
    company = models.CharField(max_length=64, unique=True)
    contact_name = models.CharField(max_length=64)
    contact_email = models.EmailField()
    contact_phone = models.CharField(
        max_length=16,
        blank=True,
        help_text="Must have only digits and an optional country code prefixed with a plus sign",
    )
    address1 = models.CharField(max_length=48, help_text="Street address, P.O. box")
    address2 = models.CharField(
        max_length=32, blank=True, help_text="Apartment, suite, unit, building, floor"
    )
    city = models.CharField(max_length=32)
    state = models.CharField(
        max_length=32, help_text="Should use 2 letter abbreviations for U.S. states"
    )
    zipcode = models.CharField(max_length=16)
    country = CountryField(blank_label="")
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["company"]

    def __str__(self):
        return self.company

    def get_pretty_contact_phone(self):
        if len(self.contact_phone) == 10:
            return f"({self.contact_phone[:3]}) {self.contact_phone[3:6]}-{self.contact_phone[6:10]}"
        elif len(self.contact_phone) in [12, 13] and self.contact_phone[0] == "+":
            return f"{self.contact_phone[:-10]} ({self.contact_phone[-10:-7]}) {self.contact_phone[-7:-4]}-{self.contact_phone[-4:]}"
        else:
            return self.contact_phone

    def get_address1(self):
        address = self.address1
        if self.address2:
            address += ", " + self.address2
        return address

    def get_address2(self):
        address = self.city
        address += ", " + self.state
        address += " " + self.zipcode
        return address

    def get_statistics(self):
        statistics = {
            "non_void_invoices_count": self.invoices.exclude(status=4).count()
        }

        # The total amount of money this partner has been billed for
        statistics["total_billed"] = Decimal("0.00")
        for invoice in self.invoices.exclude(status=4).exclude(status=0):
            statistics["total_billed"] += invoice.get_total()

        return statistics

    def get_last_invoice(self):
        return self.invoices.exclude(status=4).exclude(status=0).last()

partners/forms.py
import re

from django import forms
from django.conf import settings

from partners.models import Partner


class PartnerForm(forms.ModelForm):
    contact_phone = forms.RegexField(
        label="Contact Phone Number",
        regex=r"^\+?[0-9]+$",
        max_length=16,
        help_text="Must have only digits and an optional country code prefixed with a plus sign",
    )

    class Meta:
        model = Partner
        fields = "__all__"
        labels = {
            "partner_id": "Partner ID",
            "company": "Company / Organization / University",
            "contact_name": "Contact Name",
            "contact_email": "Contact Email",
            "address1": "Address Line 1",
            "address2": "Address Line 2",
            "state": "State / Region / Province",
            "zipcode": "ZIP / Postal Code",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = getattr(self, "instance", None)
        if instance and instance.pk:
            self.fields["partner_id"].disabled = True
        else:
            self.fields["partner_id"].required = False
            self.fields["partner_id"].help_text = "Must be exactly 3 characters long"

    def clean_partner_id(self):
        length = len(self.cleaned_data["partner_id"])
        if length not in [0, 3]:
            raise forms.ValidationError("Enter a valid Partner ID.")
        return self.cleaned_data["partner_id"]

    def clean_contact_name(self):
        if not re.match(settings.NAME_REGEX, self.cleaned_data["contact_name"]):
            raise forms.ValidationError("Enter a valid name.")
        return self.cleaned_data["contact_name"]

    def clean_contact_email(self):
        return self.cleaned_data["contact_email"].lower()

partners/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import View

from common.mixins import AccessModelMixin, NextPageMixin, PermissionsRequiredMixin
from partners.forms import PartnerForm
from partners.models import Partner
from partners.utils import generate_id


class ListView(PermissionsRequiredMixin, View):
    def get(self, request):
        partners = Partner.objects.all()
        return render(
            request=request,
            template_name="partners/list.html",
            context={"partners": partners},
        )


class CreateView(PermissionsRequiredMixin, NextPageMixin, View):
    superuser = True

    def get(self, request):
        form = PartnerForm()
        return render(
            request=request,
            template_name="partners/create.html",
            context={"form": form},
        )

    def post(self, request):
        form = PartnerForm(request.POST)
        if form.is_valid():
            partner = form.save(commit=False)
            partner.partner_id = generate_id(form.cleaned_data["company"])
            partner.save()
            messages.add_message(
                request, messages.SUCCESS, "The partner has been successfully created."
            )
            return HttpResponseRedirect(self.next)
        return render(
            request=request,
            template_name="partners/create.html",
            context={"form": form},
        )


class DetailView(PermissionsRequiredMixin, AccessModelMixin, View):
    model = Partner

    def get(self, request):
        return render(
            request=request,
            template_name="partners/detail.html",
            context={"partner": self.partner},
        )


class EditView(PermissionsRequiredMixin, AccessModelMixin, NextPageMixin, View):
    superuser = True
    model = Partner

    def get(self, request):
        form = PartnerForm(instance=self.partner)
        return render(
            request=request, template_name="partners/edit.html", context={"form": form}
        )

    def post(self, request):
        form = PartnerForm(request.POST, instance=self.partner)
        if form.is_valid():
            form.save()
            messages.add_message(
                request, messages.SUCCESS, "The partner has been successfully edited."
            )
            return HttpResponseRedirect(self.next)
        return render(
            request=request, template_name="partners/edit.html", context={"form": form}
        )


class DeleteView(PermissionsRequiredMixin, AccessModelMixin, NextPageMixin, View):
    superuser = True
    model = Partner

    def get(self, request):
        return render(request=request, template_name="partners/delete.html")

    def post(self, request):
        self.partner.delete()
        messages.add_message(request, messages.SUCCESS, "The partner has been deleted.")
        return HttpResponseRedirect(self.next)

partners/templates/partners/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create Partner{% endblock title %}
{% block subtitle %}Create a partner in the database to bill them.{% endblock subtitle %}

{% block content %}
<form novalidate method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-12 col-xl-6">
            {{ form.partner_id|as_crispy_field }}
        </div>
        <div class="col-12 col-xl-6">
            {{ form.company|as_crispy_field }}
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-12">
            {{ form.contact_name|as_crispy_field }}
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-xl-6">
            {{ form.contact_email|as_crispy_field }}
        </div>
        <div class="col-12 col-xl-6">
            {{ form.contact_phone|as_crispy_field }}
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-12 col-xl-6">
            {{ form.address1|as_crispy_field }}
        </div>
        <div class="col-12 col-xl-6">
            {{ form.address2|as_crispy_field }}
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-xl-6">
            {{ form.city|as_crispy_field }}
        </div>
        <div class="col-12 col-xl-6">
            {{ form.state|as_crispy_field }}
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-xl-6">
            {{ form.zipcode|as_crispy_field }}
        </div>
        <div class="col-12 col-xl-6">
            {{ form.country|as_crispy_field }}
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-12">
            {{ form.notes|as_crispy_field }}
        </div>
    </div>
    <hr>
    <div class="form-actions">
        <button type="submit" class="btn btn-success btn-detail">
            <i class="fas fa-check fa-fw mr-1"></i>
            Save
        </button>
        <a class="btn btn-secondary btn-detail" href="{{ request.GET.next }}">
            <i class="fas fa-times-circle fa-fw mr-1"></i>
            Cancel
        </a>
    </div>
</form>
{% endblock content %}

partners/templates/partners/delete.html
{% extends "base.html" %}

{% block title %}Delete Partner{% endblock title %}
{% block subtitle %}The partner data will be deleted.{% endblock subtitle %}

{% block content %}
<form novalidate method="post">
    {% csrf_token %}
    <div class="form-group">
        <p>
            Invoices will be kept, but any references to this partner will be replaced with generic ones.
        </p>
        <p>
            Are you sure you want to proceed?
            <br>
            This action is <span class="text-danger">irreversible</span>.
        </p>
    </div>
    <hr>
    <div class="form-actions">
        <button type="submit" class="btn btn-danger btn-detail">
            <i class="fas fa-trash fa-fw mr-1"></i>
            Delete
        </button>
        <a class="btn btn-secondary btn-detail" href="{% firstof request.GET.cancel request.GET.next %}">
            <i class="fas fa-times-circle fa-fw mr-1"></i>
            Cancel
        </a>
    </div>
</form>
{% endblock content %}

partners/templates/partners/detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ partner.company }}{% endblock title %}
{% block subtitle %}View data about the partner.{% endblock subtitle %}

{% block content %}
<div class="container-fluid no-gutters">
    <div class="row pt-3">
        <div class="col-xl-6 px-0 pr-xl-3">
            <h2 class="text-uppercase font-weight-bold">Partner Information</h2>
            <table class="table">
                <tbody>
                    <tr>
                        <th scope="row">Partner ID</th>
                        <td>{{ partner.partner_id }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Company / Organization / University</th>
                        <td>{{ partner.company }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Contact Name</th>
                        <td>{{ partner.contact_name }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Contact Email</th>
                        <td><a href="mailto:{{ partner.contact_email }}">{{ partner.contact_email }}</a></td>
                    </tr>
                    <tr>
                        <th scope="row">Contact Phone Number</th>
                        <td>{{ partner.get_pretty_contact_phone }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Address Line 1</th>
                        <td>{{ partner.address1 }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Address Line 2</th>
                        <td>{{ partner.address2 }}</td>
                    </tr>
                    <tr>
                        <th scope="row">City</th>
                        <td>{{ partner.city }}</td>
                    </tr>
                    <tr>
                        <th scope="row">State / Region / Province</th>
                        <td>{{ partner.state }}</td>
                    </tr>
                    <tr>
                        <th scope="row">ZIP / Postal Code</th>
                        <td>{{ partner.zipcode }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Notes</th>
                        <td>{{ partner.notes }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-xl-6 px-0 pl-xl-3">
            <h2 class="text-uppercase font-weight-bold">Partner Statistics</h2>
            <table class="table">
                {% with statistics=partner.get_statistics %}
                <tbody>
                    <tr>
                        <th scope="row">When did we become partners?</th>
                        <td>{{ partner.created_at|date:'DATE_FORMAT' }}</td>
                    </tr>
                    <tr>
                        <th scope="row">How many non-void invoices have been created for this partner?</th>
                        <td>{{ statistics.non_void_invoices_count }}</td>
                    </tr>
                    <tr>
                        <th scope="row">What is the last invoice that has been sent to this partner?</th>
                        {% if partner.get_last_invoice %}
                        <td><a href="{% url 'invoices:pdf' uid=partner.get_last_invoice.uid %}">{{ partner.get_last_invoice }}</a></td>
                        {% else %}
                        <td>N/A</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <th scope="row">How much has this partner been billed for?</th>
                        <td>${{ statistics.total_billed }}</td>
                    </tr>
                </tbody>
                {% endwith %}
            </table>
            <p class="text-center">Want more statistics? Create a feature request on My-Business <a
                    href="https://github.com/GDGSNF/My-Business/issues">Github</a>!</p>
        </div>
    </div>
</div>
<hr>
<div class="container-fluid no-gutters">
    <div class="row">
        <a class="btn btn-dark btn-detail" href="{% url 'partners:list' %}">
            <i class="fas fa-arrow-left"></i>
        </a>
        {% if user.is_superuser %}
        <a class="btn btn-warning btn-detail" href="{% url 'partners:edit' uid=partner.uid %}?next={{ request.get_full_path }}">
            <i class="fas fa-pen mr-1"></i>
            Edit Partner
        </a>
        <a class="btn btn-danger btn-detail" href="{% url 'partners:delete' uid=partner.uid %}?next=/partners/&cancel={{ request.get_full_path }}">
            <i class="fas fa-trash mr-1"></i>
            Delete Partner
        </a>
        {% endif %}
    </div>
</div>
{% endblock content %}

partners/templates/partners/edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Edit Partner{% endblock title %}
{% block subtitle %}Edit the partner information while keeping all the data intact.{% endblock subtitle %}

{% block content %}
<form novalidate method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-12 col-xl-6">
            {{ form.partner_id|as_crispy_field }}
        </div>
        <div class="col-12 col-xl-6">
            {{ form.company|as_crispy_field }}
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-12">
            {{ form.contact_name|as_crispy_field }}
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-xl-6">
            {{ form.contact_email|as_crispy_field }}
        </div>
        <div class="col-12 col-xl-6">
            {{ form.contact_phone|as_crispy_field }}
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-12 col-xl-6">
            {{ form.address1|as_crispy_field }}
        </div>
        <div class="col-12 col-xl-6">
            {{ form.address2|as_crispy_field }}
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-xl-6">
            {{ form.city|as_crispy_field }}
        </div>
        <div class="col-12 col-xl-6">
            {{ form.state|as_crispy_field }}
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-xl-6">
            {{ form.zipcode|as_crispy_field }}
        </div>
        <div class="col-12 col-xl-6">
            {{ form.country|as_crispy_field }}
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-12">
            {{ form.notes|as_crispy_field }}
        </div>
    </div>
    <hr>
    <div class="form-group">
        <p>The Partner ID will <span class="text-danger">not</span> change despite any modifications you make on this
            page.
        </p>
    </div>
    <hr>
    <div class="form-actions">
        <button type="submit" class="btn btn-success btn-detail">
            <i class="fas fa-check fa-fw mr-1"></i>
            Save
        </button>
        <a class="btn btn-secondary btn-detail" href="{{ request.GET.next }}">
            <i class="fas fa-times-circle fa-fw mr-1"></i>
            Cancel
        </a>
    </div>
</form>
{% endblock content %}

partners/templates/partners/list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Partners{% endblock title %}
{% block subtitle %}All the partners are listed here.{% endblock subtitle %}

{% block content %}
<table id="jsTable" class="table list-view nowrap" style="width: 100%;">
    <thead>
        <tr>
            <th scope="col">Partner ID</th>
            <th scope="col">Company / Organization / University</th>
            <th scope="col">Contact Name</th>
            <th scope="col">Contact Email</th>
            <th scope="col">
                {% if user.is_superuser %}
                <a class="btn btn-sm btn-success" href="{% url 'partners:create' %}?next={{ request.get_full_path }}">
                    <i class="fas fa-plus fa-fw"></i>
                    Create Partner
                </a>
                {% endif %}
            </th>
        </tr>
    </thead>
    <tbody>
        {% for partner in partners %}
        <tr>
            <td>{{ partner.partner_id }}</td>
            <td>{{ partner.company }}</td>
            <td>{{ partner.contact_name }}</td>
            <td><a href="mailto:{{ partner.contact_email }}">{{ partner.contact_email }}</a></td>
            <td>
                <a class="btn btn-sm btn-info" href="{% url 'partners:detail' uid=partner.uid %}" title="View Partner">
                    <i class="fas fa-eye fa-fw"></i>
                </a>
                {% if user.is_superuser %}
                <a class="btn btn-sm btn-warning" href="{% url 'partners:edit' uid=partner.uid %}?next={{ request.get_full_path }}" title="Edit Partner">
                    <i class="fas fa-pen fa-fw"></i>
                </a>
                <a class="btn btn-sm btn-danger" href="{% url 'partners:delete' uid=partner.uid %}?next={{ request.get_full_path }}" title="Delete Partner">
                    <i class="fas fa-trash fa-fw"></i>
                </a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}