common/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.urls import include, path
from django.views.generic import TemplateView

from common.views import SettingsView

urlpatterns = [
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("partners/", include("partners.urls", namespace="partners")),
    path("invoices/", include("invoices.urls", namespace="invoices")),
    path("servers/", include("servers.urls", namespace="servers")),
    path("settings/", SettingsView.as_view(), name="settings"),
    path(
        "",
        login_required(TemplateView.as_view(template_name="dashboard.html")),
        name="dashboard",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

servers/urls.py
from django.urls import path

from servers import views

app_name = "servers"

urlpatterns = [
    path("", views.ListView.as_view(), name="list"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("<int:uid>/", views.DetailView.as_view(), name="detail"),
    path("<int:uid>/edit/", views.EditView.as_view(), name="edit"),
    path("<int:uid>/delete/", views.DeleteView.as_view(), name="delete"),
]

servers/models.py
from django.db import models


class Server(models.Model):
    uid = models.IntegerField(primary_key=True)
    root_password = models.CharField(max_length=32)
    services = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_services(self):
        return self.services.splitlines()

servers/forms.py
from django import forms

from servers.models import Server


class ServerForm(forms.ModelForm):
    class Meta:
        model = Server
        fields = "__all__"
        labels = {"uid": "Linode ID", "root_password": "Root Password"}
        widgets = {
            "services": forms.Textarea(
                attrs={
                    "placeholder": "Follow the format: Service (Product) - URL\n"
                    "E.g. GDGSNF (LibreOrganize) - gdgsnf.github.io"
                }
            )
        }

    def __init__(self, *args, **kwargs):
        super().__init__(**kwargs)
        if getattr(self, "instance") and self.instance.pk:
            self.fields["uid"].disabled = True

servers/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse
from django.views import View

from common.mixins import AccessModelMixin, NextPageMixin, PermissionsRequiredMixin
from servers.forms import ServerForm
from servers.linode_api import get_bootstrap_colored_status, get_linode, get_linodes
from servers.models import Server


class ListView(PermissionsRequiredMixin, View):
    def get(self, request):
        servers = Server.objects.all()
        linodes = get_linodes()
        for server in servers:
            for linode in linodes:
                if server.uid == linode.id:
                    setattr(server, "label", linode.label)
                    setattr(
                        server,
                        "status",
                        [get_bootstrap_colored_status(linode.status), linode.status],
                    )
                    setattr(server, "region", linode.region.id)
        return render(
            request=request,
            template_name="servers/list.html",
            context={"servers": servers},
        )


class CreateView(PermissionsRequiredMixin, NextPageMixin, View):
    superuser = True

    def get(self, request):
        form = ServerForm()
        return render(
            request=request, template_name="servers/create.html", context={"form": form}
        )

    def post(self, request):
        form = ServerForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(
                request, messages.SUCCESS, "The server has been successfully created."
            )
            return HttpResponseRedirect(self.next)
        return render(
            request=request, template_name="servers/create.html", context={"form": form}
        )


class DetailView(PermissionsRequiredMixin, AccessModelMixin, View):
    model = Server

    def get(self, request):
        linode = get_linode(self.server.uid)
        if not linode:
            messages.add_message(request, messages.ERROR, "The linode is invalid.")
            return HttpResponseRedirect(reverse("servers:list"))
        status = get_bootstrap_colored_status(linode.status)
        return render(
            request=request,
            template_name="servers/detail.html",
            context={"server": self.server, "linode": linode, "status": status},
        )


class EditView(PermissionsRequiredMixin, AccessModelMixin, NextPageMixin, View):
    superuser = True
    model = Server

    def get(self, request):
        form = ServerForm(instance=self.server)
        return render(
            request=request, template_name="servers/edit.html", context={"form": form}
        )

    def post(self, request):
        form = ServerForm(request.POST, instance=self.server)
        if form.is_valid():
            form.save()
            messages.add_message(
                request, messages.SUCCESS, "The server has been successfully edited."
            )
            return HttpResponseRedirect(self.next)
        return render(
            request=request, template_name="servers/edit.html", context={"form": form}
        )


class DeleteView(PermissionsRequiredMixin, AccessModelMixin, NextPageMixin, View):
    superuser = True
    model = Server

    def get(self, request):
        return render(request=request, template_name="servers/delete.html")

    def post(self, request):
        self.server.delete()
        messages.add_message(request, messages.SUCCESS, "The server has been deleted.")
        return HttpResponseRedirect(self.next)

servers/templates/servers/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create Server{% endblock title %}
{% block subtitle %}Create a server to easily track what's stored where.{% endblock subtitle %}

{% block content %}
<form novalidate method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <hr>
    <div class="form-actions">
        <button type="submit" class="btn btn-success btn-detail">
            <i class="fas fa-check fa-fw mr-1"></i>
            Save
        </button>
        <a class="btn btn-secondary btn-detail" href="{{ request.GET.next }}">
            <i class="fas fa-times-circle fa-fw mr-1"></i>
            Cancel
        </a>
    </div>
</form>
{% endblock content %}

servers/templates/servers/delete.html
{% extends "base.html" %}

{% block title %}Delete Server{% endblock title %}
{% block subtitle %}The server information will be deleted.{% endblock subtitle %}

{% block content %}
<form novalidate method="post">
    {% csrf_token %}
    <div class="form-group">
        <p>
            The official Linode will <span class="text-danger">not</span> be deleted.
        </p>
        <p>
            Are you sure you want to proceed?
            <br>
            This action is <span class="text-danger">irreversible</span>.
        </p>
    </div>
    <div class="form-actions">
        <button type="submit" class="btn btn-danger btn-detail">
            <i class="fas fa-trash fa-fw mr-1"></i>
            Delete
        </button>
        <a class="btn btn-secondary btn-detail" href="{% firstof request.GET.cancel request.GET.next %}">
            <i class="fas fa-times-circle fa-fw mr-1"></i>
            Cancel
        </a>
    </div>
</form>
{% endblock content %}

servers/templates/servers/detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ linode.label }}{% endblock title %}
{% block subtitle %}View the server information.{% endblock subtitle %}

{% block content %}
<div class="container-fluid no-gutters">
    <div class="row pt-3">
        <div class="col-xl-6 px-0 pr-xl-3">
            <h2 class="text-uppercase font-weight-bold">Linode Information</h2>
            <table class="table">
                <tbody>
                    <tr>
                        <th scope="row">ID</th>
                        <td>{{ server.uid }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Label</th>
                        <td>{{ linode.label }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Type</th>
                        <td>{{ linode.type.label }}: ${{ linode.type.price.monthly }}0/mo</td>
                    </tr>
                    <tr>
                        <th scope="row">Operating System</th>
                        <td>{{ linode.image.label }}</td>
                    </tr>
                    <tr>
                        <th scope="row">IP Address</th>
                        <td class="d-flex justify-content-between">
                            <p class="m-0 p-0" id="ipAddress">{{ linode.ipv4.0 }}</p>
                            <button class="btn btn-sm btn-outline-secondary ml-2" id="ipAddressButton">
                                <i class="fas fa-copy fa-fw"></i>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Root Password</th>
                        <td class="d-flex justify-content-between">
                            <p class="m-0 p-0" id="rootPassword">{{ server.root_password }}</p>
                            <button class="btn btn-sm btn-outline-info ml-2" href="#" data-toggle="button" id="rootPasswordButton">
                                <i class="fas fa-eye fa-fw"></i>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Status</th>
                        <td>
                            <span class="badge badge-{{ status }} font-weight-normal text-uppercase">{{ linode.status }}</span>
                            <span class="badge badge-secondary font-weight-normal text-uppercase">{{ linode.region.id }}</span>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-xl-6 px-0 pl-xl-3">
            <h2 class="text-uppercase font-weight-bold">Services Information</h2>
            <table class="table">
                <tbody>
                    {% for line in server.get_services %}
                    <tr>
                        <th scope="row">Services</th>
                        <td>{{ line|urlize }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<hr>
<div class="container-fluid no-gutters">
    <div class="row">
        <a class="btn btn-dark btn-detail" href="{% url 'servers:list' %}">
            <i class="fas fa-arrow-left"></i>
        </a>
        <a class="btn btn-primary btn-detail" id="consoleButton" href="https://cloud.linode.com/linodes/{{ server.uid }}/lish/weblish">
            <i class="fas fa-terminal mr-1"></i>
            Launch Console
        </a>
        {% if user.is_superuser %}
        <a class="btn btn-warning btn-detail" href="{% url 'servers:edit' uid=server.uid %}?next={{ request.get_full_path }}">
            <i class="fas fa-pen mr-1"></i>
            Edit Server
        </a>
        <a class="btn btn-danger btn-detail" href="{% url 'servers:delete' uid=server.uid %}?next=/servers/&cancel={{ request.get_full_path }}">
            <i class="fas fa-trash mr-1"></i>
            Delete Server
        </a>
        {% endif %}
    </div>
</div>
{% endblock content %}

servers/templates/servers/edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Edit Server{% endblock title %}
{% block subtitle %}Edit the server information.{% endblock subtitle %}

{% block content %}
<form novalidate method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-actions">
        <button type="submit" class="btn btn-success btn-detail">
            <i class="fas fa-check fa-fw mr-1"></i>
            Save
        </button>
        <a class="btn btn-secondary btn-detail" href="{{ request.GET.next }}">
            <i class="fas fa-times-circle fa-fw mr-1"></i>
            Cancel
        </a>
    </div>
</form>
{% endblock content %}

servers/templates/servers/list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Servers{% endblock title %}
{% block subtitle %}All your active servers are listed here.{% endblock subtitle %}

{% block content %}
<table id="jsTable" class="table list-view nowrap" style="width: 100%;">
    <thead>
        <tr>
            <th scope="col">Label</th>
            <th scope="col">Services</th>
            <th scope="col">
                {% if user.is_superuser %}
                <a class="btn btn-sm btn-success" href="{% url 'servers:create' %}?next={{ request.get_full_path }}">
                    <i class="fas fa-plus fa-fw"></i>
                    Create Server
                </a>
                {% endif %}
            </th>
        </tr>
    </thead>
    <tbody>
        {% for server in servers %}
        <tr>
            <td>
                {{ server.label }}
                <span class="ml-1 badge badge-{{ server.status.0 }} font-weight-normal text-uppercase">{{ server.status.1 }}</span>
                <span class="ml-1 badge badge-secondary font-weight-normal text-uppercase">{{ server.region }}</span>
            </td>
            <td>
                {% for service in server.get_services %}
                {{ service|urlize }}
                {% endfor %}
            </td>
            <td>
                <a class="btn btn-sm btn-info" href="{% url 'servers:detail' uid=server.uid %}" title="View Server">
                    <i class="fas fa-eye fa-fw"></i>
                </a>
                {% if user.is_superuser %}
                <a class="btn btn-sm btn-warning" href="{% url 'servers:edit' uid=server.uid %}?next={{ request.get_full_path }}" title="Edit Server">
                    <i class="fas fa-pen fa-fw"></i>
                </a>
                <a class="btn btn-sm btn-danger" href="{% url 'servers:delete' uid=server.uid %}?next={{ request.get_full_path }}" title="Delete Server">
                    <i class="fas fa-trash fa-fw"></i>
                </a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}