accounts/urls.py
from django.urls import path

from accounts import views

app_name = "accounts"

urlpatterns = [
    path("", views.ListView.as_view(), name="list"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("password/reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password/reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset",
    ),
    path("create/", views.CreateView.as_view(), name="create"),
    path(
        "<int:uid>/password/change/",
        views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path("<int:uid>/", views.DetailView.as_view(), name="detail"),
    path("<int:uid>/edit/", views.EditView.as_view(), name="edit"),
    path("<int:uid>/delete/", views.DeleteView.as_view(), name="delete"),
    path("<int:uid>/type/", views.TypeView.as_view(), name="type"),
    path("shifts/create/", views.CreateShiftView.as_view(), name="shifts_create"),
    path("shifts/<int:uid>/edit/", views.EditShiftView.as_view(), name="shifts_edit"),
    path(
        "shifts/<int:uid>/delete/",
        views.DeleteShiftView.as_view(),
        name="shifts_delete",
    ),
]

common/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.urls import include, path
from django.views.generic import TemplateView

from common.views import SettingsView

urlpatterns = [
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("partners/", include("partners.urls", namespace="partners")),
    path("invoices/", include("invoices.urls", namespace="invoices")),
    path("servers/", include("servers.urls", namespace="servers")),
    path("settings/", SettingsView.as_view(), name="settings"),
    path(
        "",
        login_required(TemplateView.as_view(template_name="dashboard.html")),
        name="dashboard",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

servers/urls.py
from django.urls import path

from servers import views

app_name = "servers"

urlpatterns = [
    path("", views.ListView.as_view(), name="list"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("<int:uid>/", views.DetailView.as_view(), name="detail"),
    path("<int:uid>/edit/", views.EditView.as_view(), name="edit"),
    path("<int:uid>/delete/", views.DeleteView.as_view(), name="delete"),
]

common/forms.py
from configparser import ConfigParser

from django import forms
from django.conf import settings


class SettingsForm(forms.Form):
    invoice_template = forms.FileField(
        required=False,
        label="Invoice Template",
        help_text="Can be left empty to keep the current template",
    )
    email_host = forms.CharField(
        required=False, label="Email Host", help_text="E.g. mail.business.org"
    )
    email_port = forms.IntegerField(label="Email Port")
    email_user = forms.CharField(
        required=False, label="Email User", help_text="E.g. do-not-reply@business.org"
    )
    email_password = forms.CharField(required=False, label="Email Password")
    email_use_tls = forms.BooleanField(required=False, label="Use TLS for Email")
    weekly_hours = forms.IntegerField(
        label="Weekly Required Hours",
        help_text="The amount of hours someone should work per week",
    )
    overdue_days = forms.IntegerField(
        label="Overdue Days",
        help_text="The amount of days after which an invoice is marked as overdue (Use 0 for never)",
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Read the config.ini file
        self.config = ConfigParser(interpolation=None)
        self.config.read(settings.CONFIG_FILE)

        # Set initial values from the config file
        self.initial["email_host"] = self.config.get("email", "EMAIL_HOST")
        self.initial["email_port"] = self.config.getint("email", "EMAIL_PORT")
        self.initial["email_user"] = self.config.get("email", "EMAIL_USER")
        self.initial["email_password"] = self.config.get("email", "EMAIL_PASSWORD")
        self.initial["email_use_tls"] = self.config.getboolean("email", "EMAIL_USE_TLS")
        self.initial["weekly_hours"] = self.config.getint("accounts", "WEEKLY_HOURS")
        self.initial["overdue_days"] = self.config.getint("invoices", "OVERDUE_DAYS")

    def clean_email_port(self):
        if self.cleaned_data["email_port"] not in range(65535):
            raise forms.ValidationError("Enter an integer between 0 and 65535.")
        return self.cleaned_data["email_port"]

    def clean_weekly_hours(self):
        if self.cleaned_data["weekly_hours"] < 0:
            raise forms.ValidationError("Enter a positive integer.")
        return self.cleaned_data["weekly_hours"]

    def clean_overdue_days(self):
        if self.cleaned_data["overdue_days"] < 0:
            raise forms.ValidationError("Enter a positive integer.")
        return self.cleaned_data["overdue_days"]

    def save(self):
        self.config.set("email", "EMAIL_HOST", self.cleaned_data["email_host"])
        self.config.set("email", "EMAIL_PORT", str(self.cleaned_data["email_port"]))
        self.config.set("email", "EMAIL_USER", self.cleaned_data["email_user"])
        self.config.set("email", "EMAIL_PASSWORD", self.cleaned_data["email_password"])
        self.config.set(
            "email", "EMAIL_USE_TLS", str(self.cleaned_data["email_use_tls"])
        )
        self.config.set(
            "accounts", "WEEKLY_HOURS", str(self.cleaned_data["weekly_hours"])
        )
        self.config.set(
            "invoices", "OVERDUE_DAYS", str(self.cleaned_data["overdue_days"])
        )

        with open(settings.CONFIG_FILE, "w") as f:
            self.config.write(f, space_around_delimiters=False)

common/views.py
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render
from django.views import View

from common.forms import SettingsForm
from common.mixins import PermissionsRequiredMixin


class SettingsView(PermissionsRequiredMixin, View):
    superuser = True

    def get(self, request):
        form = SettingsForm()
        return render(
            request=request, template_name="settings.html", context={"form": form}
        )

    def post(self, request):
        form = SettingsForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            new_template = request.FILES.get("invoice_template", None)
            if new_template:
                with open(settings.TEMPLATE_FILE, "wb+") as destination:
                    for chunk in new_template.chunks():
                        destination.write(chunk)
            messages.add_message(
                request, messages.SUCCESS, "The settings have been sucessfully saved.",
            )

            form = SettingsForm()
        return render(
            request=request, template_name="settings.html", context={"form": form}
        )

common/templates/includes/messages.html
{% if messages %}
<div class="fixed-top">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true"><i class="fas fa-times"></i></span>
        </button>
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}

common/templates/includes/sidebar.html
{% load static %}
<div class="sidenav">
    <a class="link-unstyled" href="https://gdgsnf.tech" style="margin: 0">
        <img class="img-fluid d-block mx-auto" src="{% static 'img/logo.png' %}">
    </a>
    <div class="sidenav-controls">
        {% if user.is_authenticated %}
        <a href="{% url 'dashboard' %}"><i class="fas fa-clone fa-fw mr-2"></i>Dashboard</a>
        <a href="{% url 'accounts:shifts_create' %}"><i class="fas fa-clock fa-fw mr-2"></i>Track Hours</a>
        <div>
            <hr>
        </div>
        {% if user.is_superuser %}
        <a href="{% url 'accounts:list' %}"><i class="fas fa-users fa-fw mr-2"></i>Accounts</a>
        {% endif %}
        <a href="{% url 'invoices:list' %}"><i class="fas fa-file-invoice-dollar fa-fw mr-2"></i>Invoices</a>
        <a href="{% url 'partners:list' %}"><i class="fas fa-user-friends fa-fw mr-2"></i>Partners</a>
        <a href="{% url 'servers:list' %}"><i class="fas fa-server fa-fw mr-2"></i>Servers</a>
        <div>
            <hr>
        </div>
        {% if user.is_superuser %}
        <a href="{% url 'settings' %}"><i class="fas fa-cog fa-fw mr-2"></i>Settings</a>
        {% endif %}
        <a href="{% url 'accounts:detail' uid=user.uid %}?personal=true"><i class="fas fa-user fa-fw mr-2"></i>My
            Account</a>
        <a href="{% url 'accounts:logout' %}"><i class="fas fa-sign-out-alt fa-fw mr-2"></i>Log out</a>
        {% else %}
        <a href="{% url 'accounts:login' %}"><i class="fas fa-sign-in-alt fa-fw mr-2"></i>Login</a>
        <a href="{% url 'accounts:password_reset' %}"><i class="fas fa-key fa-fw mr-2"></i>Reset Password</a>
        {% endif %}
    </div>
    <button type="button" class="btn sidenav-button" onclick="toggleSidebar()">
        <i class="fas fa-chevron-right"></i>
    </button>
</div>